version: "3.4"

x-hong-kong:
  dockerfile: "dockerfile"
  route: "/"

# Test4

services:
  rj-router:
    image: therileyjohnson/rj-site-router:latest
    restart: always
    # volumes:
    #   - ./secrets:/secrets
    ports:
      - "8009:80"
      # - "443:443"
