version: "3.5"

x-hong-kong:
  buildInfo:
    - dockerfile: "dockerfile"
      name: "rj-router"

services:
  rj-router:
    image: therileyjohnson/rj-site-router_rj-router:latest
    restart: always
    volumes:
      - ./secrets:/secrets
    ports:
      - "443:443"
    networks:
      - rjnet

networks:
  rjnet:
    name: RJnet
# CI 1
