version: "3.5"

x-hong-kong:
  buildInfo:
    - dockerfile: "dockerfile"
      name: "rj-router"

services:
  rj-router:
    build: .
    env_file:
      - dev.env
    entrypoint:
      ["/server", "-dd", "localhost:9900", "-d", "-dh", "http://rj-site"]
    restart: always
    ports:
      - "9900:9900"
    networks:
      - rjnet

networks:
  rjnet:
    name: RJnet
