version: "3.4"

x-hong-kong:
  dockerfile: "dockerfile"

services:
  rj-router:
    image: therileyjohnson/rj-site-router:latest
    restart: always
    volumes:
      - ./secrets:/secrets
    ports:
      # - "80:80"
      - "443:443"
